### ISSUE TITLE
Usage with SASS

### ISSUE THREAD

**Issue by marcofugaro** [eqcss/eqcss#10]
Sorry if not a real issue, but how would I go about using element queries with SCSS?

I mainly write in SCSS and compile it, obviously now if I use element queries it throws and error during compilation. What would you recommend?

**Comment by tomhodgins** [comment]
Hey Marco! Thanks for the interest, and that’s definitely a good question. I don’t have a lot of experience with SASS/SCSS since at the end of the day - it is simply a method for outputting a large volume of regular CSS. I prefer to hand-write only the CSS which I need for a layout, so adding in a compilation stage between writing my CSS and being able to view it in the browser is a major stumbling block to productivity, and greatly limits the devices and situations where I am free to experiment with writing code.

The premise of EQCSS is to extend CSS to reach the things that regular CSS can’t reach or help you with - so using a tool that outputs large volumes of regular CSS doesn’t get you any closer to that target. After dabbling with SASS/SCSS I find it to be most useful for a few specific cases:
- Browser prefixing, especially with complicated CSS animations where the properties are also different by browser
- Expressing CSS design patterns at a higher level when teaching/demonstrating them to others
- Creating modifiable source code pattern for the purpose of outputting many similar CSS files (theme/widget builders)

I may not be able to show you how integrate EQCSS with SASS/SCSS, but if you can explain to me what you’re trying to accomplish by using SCSS I’m sure I can show you a simpler way of accomplishing the same thing with CSS alone, or CSS plus EQCSS.

With element queries and scoped styles your CSS _comes alive_ when the page loads! That’s not where things end, that’s the beginning. Styles can change as the user scrolls, clicks, types, or as new elements are added or removed from the layout. These are all things that regular CSS (and thus SASS and SCSS) are powerless to style.

Writing EQCSS can be a shift in how you approach writing CSS, and for many that shift may represent the freedom to leaving behind preprocessors like Less/Sass/Stylus and the workflow of compiling CSS before being able to preview it in browser.

I’d love to help, could you put a snippet of your SCSS styles up on Codepen with an explanation of what you would like to do that I can try to refactor to CSS + EQCSS? That might be the best way of bridging the gap between your knowledge and mine.

EDIT: I did make a [teeny tiny test file with EQCSS + SASS](http://codepen.io/tomhodgins/pen/bVJMRQ), but due to things like SASS not understanding EQCSS's meta-selectors, like `$this` really limited the usefulness of SASS+EQCSS for me. Is there a way to escape or ignore a character in SASS? If SASS could be used to output CSS with EQCSS intact, the EQCSS could take it from there at page load.

**Comment by marcofugaro** [comment]
Hey Tom, sorry for the late reply. 
Yes I respect your choice of not using SCSS personally, but nowadays a very big slice of frontend devs use it daily, so that it's considered standard in the industry, even over other preprocessors.
I personally like it for the nesting capabilities so that I can keep my code readable and DRY, and not worrying about vendor prefixes as you said.

I just want to use eqcss in my SCSS.

Yes the problem are the $this $root and $prev as you said, since $ means variable in SCSS, I can't think of a workaround to this, [I tried with interpolation on your example](http://codepen.io/marco_fugaro/pen/ZWrxpo), but it didn't work.

**Comment by tomhodgins** [comment]
I think this may be a question for SCSS folks. If you can find a way to embed EQCSS in SCSS and have the compiler it ignore and bypass it and output it as-is, or if you can find a way to write valid SCSS and convince the compiler to output the corresponding correct EQCSS it will work when loaded in the browser with EQCSS.js

Perhaps when you want to make use of style scoping and the meta-selectors you could include those styles in separate stylesheets? EQCSS also supports the loading of styles under the `<script type=text/eqcss>` type, so if you have a stylesheet named `styles.eqcss` you could also load it like this:

```
<script src=styles.eqcss></script>
```

And the contents of the `.eqcss` file would be the same as CSS, or CSS with added EQCSS features. Some problems I use EQCSS to solve amount to just a few lines per website, like [wrapper-free responsive videos](http://staticresource.com/template/plugins/video-scaling).

Hope the SCSSlings can shed some light on this for you :)
