### ISSUE TITLE
Question: Multiple element queries. What am I doing wrong

### ISSUE THREAD

**Issue by caraya** [eqcss/eqcss#11]
I'm figuring out how to use eqcss and I'm having a problem. 

In [https://gist.github.com/caraya/29754c23543bde2d1c7b08d6b1eee2a5](https://gist.github.com/caraya/29754c23543bde2d1c7b08d6b1eee2a5) I created to element queries, one with minwidthpixel and the other one with maxwidthpercents. The first one works as intended but the second one doesn't. 

I'm pretty sure I'm doing something wrong but can't figure out what it is.  Can anyone point me out to where the mistake is?

Thanks

**Comment by tomhodgins** [comment]
Hi Caraya! Glad you're checking out EQCSS and playing around with the new queries. So what's going on here is actually that the code is running exactly as written, but that may not be what you're looking for.

So in your demo, you've got two `div` elements, one with `class=minwidthpixels` and one with `class=maxwidthpercent`. Both of these elements are 100% wide (due to `div` being a block level element) so as long as the page is wider than `500px`, the `(min-width: 500px)` element query will apply.

Now for the `(max-width: 50%)`, that will apply any time the element is less than `50%` the width of its container. Since `div` is block, it's `100%` wide all the time (in other words, too wide for the demo). In order for that style to apply as-written, you'll need to constrain the element to less than 50% of its parent container's width. Or else you could flip the query's logic over from `max-width` to `min-width: 50%` and it would apply all the time (since the element is 100% wide).

Also just as a side-note, you can use `<script type=text/eqcss>` or `<style>` to write EQCSS-enhanced CSS, but you don't need the `type=text/eqcss` on `<style>` tags! You can also include EQCSS in any external CSS stylesheets linked into a page where EQCSS.js is loaded just as regular .css files :)

Here's an updated pen with the second `div` constrained to `49%` wide, so the `max-width` query applies at all times: http://codepen.io/tomhodgins/pen/eZjKva

**Comment by caraya** [comment]
Got it. Thanks for the clarification

**Comment by tomhodgins** [comment]
Happy to help! Feel free to ask about anything if you have any more questions or ideas as you use EQCSS 😊
