### ISSUE TITLE
Working with a Sass preprocessor?

### ISSUE THREAD

**Issue by maxx1128** [eqcss/eqcss#14]
I'm already basically in love with this tool, but one issue I've been struggling with:

I often use gulp-sass or one of several other Sass preprocessors for my CSS code. Using @element queries blocks this process due to the conflicting syntax. I'm currently looking into ways for gulp-sass to skip or ignore these sections, although then I couldn't use Sass variables in the queries which would be a bummer.

Any ideas or future plans for this conflict? I'm eager to fix it since it being Sass-friendly would be a major boost.

**Comment by maxx1128** [comment]
Noticed this was a previous issue, closing it now

**Comment by tomhodgins** [comment]
Hey Max! Thanks for your enthusiasm in checking out EQCSS!

I've experimented a little bit, but still haven't figured out how to exclude the syntax from Sass/SCSS output. Why are there two Sass syntaxes anyway?

I do have an idea for your workflow though! If you want to write EQCSS and write that alongside Sass in the same project, instead of putting it in the same file you can locate your EQCSS-powered queries in a separate CSS file, or in an EQCSS script file like `styles.eqcss` that would get linked in like this `<script src=styles.eqcss type=text/eqcss></script>`. You could also create a `<script type=text/eqcss></script>` tag and put the styles right inside there too.

Hopefully that can help give you some ideas how you could go about taking advantage of the power of element queries without changing up your existing workflow too much :)

Happy hacking!

**Comment by maxx1128** [comment]
Thanks, will definitely look into that! Although my ideal is using the element queries with other parts of Sass like variables, so I'll look into other ways around this too.

One idea I had: would there be a way to change the EQCSS syntax in an alternate version so there aren't any conflicts? I know the main ones are with $root, $this, and the like, so changing their syntax may be enough.

**Comment by tomhodgins** [comment]
@maxx1128 Yes, the part of the EQCSS source code that replaces these meta selectors (`$this`, `$parent`, `$prev`, `$next`, and `$root`) is here: https://github.com/eqcss/eqcss/blob/gh-pages/EQCSS.js#L661

Just as a test, I added extra lines that also swapped out these keywords `¡this`, `¡parent`, `¡prev`, and `¡next`, and `¡root` with the same thing, and it works!

```
// Replace "¡this" with "[element_guid]"
css_code = css_code.replace(/¡this/g, "[" + element_guid + "]");

// Replace "¡parent" with "[element_guid_parent]"
css_code = css_code.replace(/¡parent/g, "[" + element_guid_parent + "]");

// Replace "¡prev" with "[element_guid_prev]"
css_code = css_code.replace(/¡prev/g, "[" + element_guid_prev + "]");

// Replace "¡next" with "[element_guid_next]"
css_code = css_code.replace(/¡next/g, "[" + element_guid_next + "]");

// Replace "¡root" with html
css_code = css_code.replace(/¡root/g, "html");
```

This lets you use EQCSS syntax with code like this:

```
@element 'html' {
  ¡this {
    background: red;
  }
}
```

…so there's that.

If you're desperate you can add those lines to your file beside the existing ones and add this support yourself, but I'm not sure if using `¡this` is going to be easy/correct in sass/scss.

I'm not a big Sass user myself, so I'm curious what _would_ make a good Sass-compatible alternative mode to the `$` for meta-selectors? We won't be removing the dollar sign from EQCSS (to support the existing code out there that uses it) and I'm hesitant to double up lines of code (because the plugin is so tiny) but this is an issue more than one user has raised, and I'm sure more users will probably be asking about in the future.

So thanks for raising the issue, we'll think about this and likely roll out some kind of Sass-compatible alternative to these meta-selectors once we can figure out what we should call it, and how to add it in a code-efficient way.

For now you can play around with the `eqscss.js` file I've attached here as a proof of concept ^_^

[eqscss.js.zip](https://github.com/eqcss/eqcss/files/298120/eqscss.js.zip)

**Comment by maxx1128** [comment]
For a Sass-compatible alternative, the only other variable syntax I know that's used is the interpolation syntax, which would be **#{$var}**. I've always thought it to be a little messy but it'd work just fine for me.

Also interesting note here: I tried something similar with changing the syntax on some Codepen examples, and my experiments worked fine with the SCSS preprocessor, but not the Sass preprocessor. This makes sense since SCSS is written much closer to CSS (hence the name I guess). But when I tried it in some .scss files in my gulp-workflow, it was breaking again.

So close.

But I'll definitely keep playing around with the code, mainly since having this plugin Sass-compatible would've fix, and likely will fix, the bulk of the issues I've had in work and side projects for the past ever. So I'm not quitting this journey easily!

**Comment by maxx1128** [comment]
Also, here's the CodePen I'm referring to where I'm editing the code:

http://codepen.io/max1128/pen/ZOGyzx

**Comment by tomhodgins** [comment]
@maxx1128 What do you think about the ability to replace any of the meta selectors (`$this`,`$parent`,`$root`,`$prev`,`$next`) with a version, prefixed by `eqcss_`? So you would be able to use them as `eqcss_this`, `eqcss_parent`, `eqcss_root`, `eqcss_prev`, `eqcss_next`?

Here's a demo of that working - I think it should pass SCSS. How would that work for your workflow? http://codepen.io/tomhodgins/pen/XKbamW

**Comment by maxx1128** [comment]
@tomhodgins That should work just fine, although in my pen I went with replacing the $ with a -. Mainly since that's less characters and I'm lazy...

Anyway, I'll give both versions a shot in my gulp workflow. Although last time I tried it broke for some reason. If on your pen you switch the preprocessor from "SCSS" to "Sass" that's the same result from mine. I'm currently using gulp-sass, but I'll switch over to gulp-scss and see if that works. If so, I'll weep joyfully and share the news here.

**Comment by tomhodgins** [comment]
@maxx1128 & @marcofugaro - We've just pushed [a patch (v1.1.1)](https://github.com/eqcss/eqcss/releases/tag/v1.1.1) that should take care of this!

Here's a demo showing how the `eq_` prefixes work with SCSS: http://codepen.io/tomhodgins/pen/XKbamW

Thanks for your patience, hope this helps!

**Comment by maxx1128** [comment]
Thank you!

I gave this a shot in my workflow with gulp-sass, but for some reason it's still not working there! However it's very close. I think the issue is task runners like gulp output Sass differently than Codepen does, likely since it uses Node. Regardless, the syntax I'm putting in my .scss file is:

```
@element 'h2' {
  eq_parent: {
    background: $brandHighlight;
  }
}
```

(had to add the colon due to it breaking the SCSS syntax for some reason)
and the output is:

```
@element 'h2' {
  eq_parent-background: #fc0;
}
```

However if I reach into the CSS file that's output and manually change it to:

```
@element 'h2' {
  eq_parent { background: #fc0; }
}
```

then it works!

I get the feeling if this is solved then it should work for other preprocessors using node-sass, which would likely be most of the people looking to use this outside of Codepen. It looks like if this patch also has a small change in the output, based on if the `eq_` prefix if used, things should be set!

**Comment by maxx1128** [comment]
I think the issue is it's reading the `eq_` selector as the first part in a property-value pair, which is why it needs the colon and is throwing off the outputted CSS in this way. I'll be playing with the SCSS to see if there's a way around this.

**Comment by maxx1128** [comment]
Wait, turns out it was my bad. I was using two tools to edit output CSS, to combine media queries and remove unused CSS, and they were tripping over the output. Removed those and it's working fine now!

Thank you very much for the patch! Really can't wait to work this into some other projects I have now.

**Comment by tomhodgins** [comment]
@maxx1128 I'm not sure, I've installed the sass gem on my computer and created a test file:

```
$color: red;

@element 'html' {
  eq_this {
    background: $color;
  }
}
```

And when I run it through sass this is my output:

```
@element 'html' {
  eq_this {
    background: red; } }
```

Which should be what we're looking for. If I add that to an HTML page with EQCSS-enabled it runs! What are you using besides Codepen or the Sass gem to convert files?

![sass-cli](https://cloud.githubusercontent.com/assets/955601/15824649/34bdf2f2-2bce-11e6-80cd-395d97ce953c.png)

**Comment by maxx1128** [comment]
I can confirm again it's working via Sass now for me, just tested out adding an extra border to buttons based on their character amounts.

```
@element '.btn' and (min-characters: 6) and (max-characters: 10) {
  eq_this {
    border: container(border, thick);
  }
}
```

Result is below:

<img width="212" alt="screen shot 2016-06-06 at 10 44 59 am" src="https://cloud.githubusercontent.com/assets/10790736/15825998/d4160e20-2bd3-11e6-94db-f3216fedc4d3.png">

**Comment by tomhodgins** [comment]
:D Looking good @maxx1128 

Hope you have fun experimenting with multi-dimensional responsive queries! Let me know if you have any more questions once you get using it :)
