### ISSUE TITLE
min-scroll-y not triggering on body

### ISSUE THREAD

**Issue by dirtyredz** [eqcss/eqcss#20]
I was originally using some JS to apply a class at 50% body scroll. I switched over to EQCSS.js and the attributes are only applied after clicking anywhere in view port. if i don't click the attributes are not applied.

`@element "body" and (min-scroll-y: 50%) { /*or using 300px*/
  aside#ScrollTop {
    opacity: 1;
    right: 0;
  }
}`

for the sake of argument/debugging i also removed all js even jQuery, and the above issue was persistent.

Chrome Version 51.0.2704.103 m

**Comment by dirtyredz** [comment]
Quick fix for this issue is to call:

`$(window).scroll(function () {
            EQCSS.apply()
});`

**Comment by tomhodgins** [comment]
Hi @dirtyredz!

Thanks for pointing this out, browsers think about `body` and `html` differently than the other elements when it comes to the scrolling, so in places where I've relied on watching the entire page scroll I will use `html, body` as my selector so it works everywhere.

For now you are able to work around this issue by adding the following line of JavaScript to the page. This will instruct EQCSS to recalculate whenever the page scrolls, with a capped limit.

```
<script>
  window.addEventListener("scroll", EQCSS.throttle);
</script>
```

Right now the scroll event is working properly for elements inside the `body`. We'll get this fixed in a future patch. Here's some HTML for a working demo that does what you want:

```
<body>
<style>
  html,body {
    min-height: 200%;
  }
  @element 'html,body' and (min-scroll-y: 50%) {
    $this {
      background: red;
    }
  }
</style>
<script src=http://elementqueries.com/EQCSS.js></script>
<script>
  window.addEventListener("scroll", EQCSS.throttle);
</script>
```

**Comment by dirtyredz** [comment]
Awesome, TY for your quick reply and a further TY for an articulated fix for my issue. Ive already implemented your fix in-place of mine and it is working as expected. Looking forward to using EQCSS in more areas of my web page.

**Comment by tomhodgins** [comment]
Wow that's great to hear! I'll go ahead and close this for now, and I'll make sure to send you an update when a fix for this is included in a release. Let me know if you have any more questions as you get started, and feel free to drop by the [EQCSS chat on Gitter](https://gitter.im/eqcss/eqcss) with questions or ideas any time :)

**Comment by tomhodgins** [comment]
I'm just playing around with ideas for this now and I think I have a solution. I'll need to test it in all browsers, and I'll ask @xem about the most efficient way of including the fix in EQCSS.js before making a new release, but I think a fix is coming soon :)

Here's the fix I'm currently testing:

[eqcss-scroll-fix.zip](https://github.com/eqcss/eqcss/files/362826/eqcss-scroll-fix.zip)
