### ISSUE TITLE
Sass/Scss compilation -  Quick solution

### ISSUE THREAD

**Issue by KennethJoris** [eqcss/eqcss#26]
This mixin will compile '@element' without any errors:

Wrapping the string into comments tags makes the scss compiler think its a scss comment. The scss will compile as valid. The trick is the output wil be un-commented.
(be carefull with mixin double and single quotes)

source: [stackoverflow](http://stackoverflow.com/questions/24082703/escaping-and-in-sass)

scss mixin:

```
@mixin raw ($string) {
  $string: '*/#{$string}/*';
  /*#{$string}*/
}
```

use:

```
@include raw('
    @element "body" and (min-width: 480px) {
        $this {
            background: gold;
        }
    }
');
```

css output:

```
/**/@element "body" and (min-width: 480px) { $this {background: gold;} }/**/
```

**Comment by tomhodgins** [comment]
Thanks @Genenenenaam! Is there a way that SCSS users package and share their mixins? This could be a downloadable resource

**Comment by tomhodgins** [comment]
Hey @Genenenenaam! I had copied this code into a demo on Codepen, but I just realized the pen was set to private. It's public now, so people can play with this and fork it, or copy/paste into their code pretty easily.

http://codepen.io/tomhodgins/pen/VKZZwA/?editors=0100

Thanks so much for sharing this code, it's something people have asked about in the past and I hadn't quite been able to figure out how to escape :D

**Comment by JawsomeJason** [comment]
@tomhodgins This should definitely be a "tip" on the README.

**Comment by scooterlord** [comment]
Hello and sorry for reopening this. I've been having issues with EQCSS in my project and narrowed down the issue to the sass preprocessor. Although the code is compiled properly, it's not working - pasting the eqcss queries directly on the compiled css works though. 

Tried the raw mixin and getting the same issues. Any ideas?

**Comment by tomhodgins** [comment]
Hi Nick!

Thanks for checking out EQCSS, and sorry you're having a conflict with the SASS compiler. I can't seem to find your comment on Github at all so I'll reply by email :)

Are you able to show me a sample of EQCSS code that SASS has output that doesn't work? I should be able to look at what it's outputting and be able to tell if there's a syntax problem present. Or a sample of SASS + EQCSS you're trying to compile so I can fiddle with it and see if I can convince SASS to output working code?

I'm not a SASS super user—I usually write my CSS by hand—but I'll take a peek and see what I can think of.

Alternatively to working around EQCSS syntax in SASS, what about keeping your EQCSS queries in a non-SASS-compiled stylesheet? I feel like it's more work to get SASS to output code you know you want than to just write what you want and forgo compiling it :D

Hope you're having a wonderful day,
Tommy

**Comment by scooterlord** [comment]
Hello Tom,
thanks for your reply. I was struggling for hours to get it to work, and a minute after I posted the comment I found out what was wrong. Although I had used the mixin above, I had forgotten to comment out the initial code in another sass partial, so it was compiled twice.

Truth is, this should be definitely added to the docs. Even without the mixin, the code compiled properly to css, but was not working. Have no idea why. Keeping the code in vanilla CSS worked without issues.

**Comment by tomhodgins** [comment]
Hi Nick!

I'm hoping to get some proper documentation created for EQCSS, currently there's no obvious spots to put this where people will find it :/ Would you expect to find this sort of documentation here on Github in the Wiki, on the website? What would be useful for a location for documentation? So far all of the stuff written about EQCSS has been in article form, spread across a number of different sites.

We also see questions about Stylus, Less, PostCSS, and using EQCSS with other tools like Angular, React, and Vue, and others. To some degree I'll be relying on users of those tools to help bridge the gaps in knowledge as I can't be an expert on every tool EQCSS can be used with. I can explain how to write EQCSS and describe precisely what EQCSS needs in order to work though.

One thing I'm hoping to do documentation-wise is write an actual spec proposal for the syntax EQCSS uses for container-style element queries. Once an actual proposal for a standardized syntax has been made I think a lot more tools like PostCSS and SASS would feel more comfortable adding their own support for element queries in their own tools, but without even so much as a written spec to propose I doubt any of those tools would do anything from their end to support EQCSS specifically.

Exciting things are coming, with a lot of typing left to do :)

**Comment by scooterlord** [comment]
Good to hear that you are putting so much effort in the plugin - totally worth it though.

Concerning the documentation I would have it in all three places - Github, website and Wiki. I would add a separate section and name it something like 'Pre-processors support/compatibility' and add all pre-processors information below - LESS, SASS or whatever else.

D3.js allows documentation to be freely added by the community, so you might also consider this.

**Comment by tomhodgins** [comment]
Hi @scooterlord, I've created a [wiki page](https://github.com/eqcss/eqcss/wiki/Using-EQCSS-with-CSS-Preprocessors) here on Github that links to @thejase's solution, as well as information for each preprocessor. As more users contribute knowledge like this we now have a spot to sort, store, and retrieve this information :D Thanks for the encouragement!

**Comment by scooterlord** [comment]
Keep it up buddy! Keep in mind that every time you give, to the community, you shall receive it one way or another. :)
