### ISSUE TITLE
Geometric demo does not work until click

### ISSUE THREAD

**Issue by alokinsoft** [eqcss/eqcss#30]
http://elementqueries.com/demos/geometric.html

![image](https://cloud.githubusercontent.com/assets/1062809/17332602/f4b924d2-58ec-11e6-9869-74f71112958c.png)

The error is on this line:
height: eval("scrollWidth")px;

It initially evaluates as 0 until you click in the body somewhere, or resize the window.

**Comment by tomhodgins** [comment]
Hi @alokinsoft! Thanks for pointing this out :D

This seems to be something that has happened when we added `EQCSS.throttle()`

For now, this demo can be fixed by adding:

```
EQCSS.domReady(function(){
  EQCSS.apply();
});
```

It's supposed to run `EQCSS.throttle()` now instead but it seems to be running the first time perhaps before it should… I'll keep investigating, but I'll fix the demos right away!
