### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by seancurtis** [eqcss/eqcss#33]
Would love to use this plugin, but I'm hesitant of using anything that doesn't include tests...

**Comment by gajus** [comment]
@seancurtis It is an open source project. ¯_(ツ)_/¯

**Comment by tomhodgins** [comment]
Hey @seancurtis! I've talked to a few testy developers who have told me that EQCSS isn't written in a very 'unit testable' way, and when they explain to me how to make it testable you would need to break it apart and make many functions with testable outputs, etc. But since EQCSS only runs in the browser dealing with rendered elements after the page has fully loaded, I'm not even sure how you would go about testing parts of it in this way.

It might make sense for a large application or for a large or confusing codebase, but the existing codebase is really tiny and written to be very straightforward. For a plugin of this size (<5kb) what is the benefit of this sort of testing?

We do have things that we call 'tests' written for EQCSS, but these are all 'functional tests'. There are the demos that run on the page at http://elementqueries.com which demo each feature, as well as Maxime's tests he uses during development at http://elementqueries.com/test.html

When doing Firefox bugfixing I produced a stripped-down feature test and located at http://staticresource.com/fftest.html just for the purpose of testing all features for browser support.

And there are 30+ functional tests that can be run in the /demo folder: https://github.com/eqcss/eqcss/tree/gh-pages/demos

If you're aware of a way to streamline the sort of front-end functional testing we do then I'm open to suggestions, but I don't think you should be hesitant to start playing around with it in the meantime!

If you want to jump right in, try forking an EQCSS-enabled pen on Codepen: http://codepen.io/search/pens?q=eqcss&limit=all&order=popularity&depth=everything&show_forks=false

**Comment by tomhodgins** [comment]
Hey @seancurtis, I've just added 32 feature tests to http://elementqueries.com/tests which can be quickly loaded in browsers to test individual features. Each square (32 total) should be lime green if the test passes :D
