### ISSUE TITLE
When resizing fast with a calc() for the width, there are problems with the div resizing for a split second

### ISSUE THREAD

**Issue by timfisher** [eqcss/eqcss#36]
I have made a jsfiddle to illustrate the problem if you resize the window from large resolution to small, I am getting the problem while trying to create a flexbox type central column that is compatible with ie9. When the screen is resized fast there is a split second where the middle box is deformed before resizing properly. 

JsFiddle here https://jsfiddle.net/ra32aLff/1/

**Comment by tomhodgins** [comment]
Hey @timfisher! Thanks for checking out EQCSS - I have used EQCSS to replicate flexbox-like layouts when I have needed to support older browsers so it's definitely a nice option for this sort of task. Here's an example of the same layout done in Flexbox, EQCSS, and vanilla JavaScript that all behave the same way: http://codepen.io/collection/XoLGRV/

The issue you are seeing in your fiddle is the plugin running according to design, and the delay you are seeing is due to the throttle we placed on how frequently EQCSS can recalculate (it runs `EQCSS.apply()` no more frequently than every 200ms). Older versions of EQCSS (before v.1.2.0) didn't have this throttle, and would recalculate very enthusiastically - and this worked great in all browsers except Firefox.

Try adding this line of JavaScript to your demo:

```
window.addEventListener('resize',EQCSS.apply)
```

This will run `EQCSS.apply()` immediately (bypassing the throttle) as often as the window resizes. It is probably overkill for most use-cases, but this will get rid of that delay you notice. You'll have to test performance on the page you're building to ensure that it performs adequately. I'd keep an eye on Firefox as the worst offender though.

alternatively there are older versions of EQCSS hosted on https://cdnjs.com/libraries/eqcss , and any version before [v1.2.0](https://github.com/eqcss/eqcss/releases/tag/v1.2.0) might work if you really don't need Firefox support (like if EQCSS is being used for IE-only styles and won't be loaded for FF for example).

Hope this helps! If you have any questions as you're working with EQCSS you can also feel free to as in Gitter channel as well: https://gitter.im/eqcss/eqcss

**Comment by timfisher** [comment]
@tomhodgins I tried 1.1.1 and it seems fine even in Firefox, thanks for the help
