### ISSUE TITLE
Is Css eval() functionality dangerous?

### ISSUE THREAD

**Issue by dariuszsikorski** [eqcss/eqcss#38]
Hi, while browsing the eqcss features i stumbled on `eval('')` functionality inside css file. Does this allow to inject custom js code by the visitors? Or does it give visitor more privilliges in code execution than regular browser console? If so, then this feature should be taken under some consideration.

**Comment by tomhodgins** [comment]
Hi @dariuszsikorski, thanks for your question! I haven't had a chance to write up a good FAQ for EQCSS yet so I appreciate questions like these because it reveals what people are curious to know.

Before we called it `eval("")` we had named it `var("")` and originally it was intended to simply return the value of a JS variable inside CSS. If you had set `var name = 'Jose'` on the page in JS and then used `var("name")` in your EQCSS, the resulting CSS output on the page would simply have contained 'Jose' where `var("")` had been. However with the introduction of native CSS variables to use the `var()` syntax we thought we should switch our syntax to something else so it wouldn't conflict when native CSS variables get browser support. `eval("")` was what we chose to rename it to, and have been using since.

Originally there were also some harsh limits to what you could write inside `eval("")` including no more than 3 levels of (nesting) inside brackets. Also, there was no shared context between the element selected by the element query, and the JavaScript being run.

Now we have switched it around so `eval("")` can access JS variables, you can nest as deep as you like (write entire functions inside your CSS if you wanted to) as well as compute one-liners or run JS functions from your CSS and use whatever gets returned.

You can see the source for this feature (15 lines of code) starting at line 755 of EQCSS.js: https://github.com/eqcss/eqcss/blob/gh-pages/EQCSS.js#L755

```
// Replace eval(xyz) with the result of try{with(element){eval(xyz)}} in JS
css_code = css_code.replace(
  /eval\( *((".*?")|('.*?')) *\)/g,
  function(string,match){
    var $it = elements[j];
    var ret = "";
    try{
      with($it){ret = eval(match.slice(1,-1))}
    }
    catch(e){
      ret = "";
    };
    return ret;
  }
);
```

More surprising than the `eval("")` might actually be the fact that when it evaluates that line of JS it's doing it from the context of the selected element (`with($it){ //code from eval("") run here  }`).

This means that things like:

```
<a href=#>Hello </a>
<style>
  @element 'a' {
    $this:before {
      content: 'eval("$it.innerHTML")';
    }
  }
</script>
```

and 

```
content: 'eval("innerHTML")';
```

Would both evaluate to `content: 'Hello ';` with or without the `$it`, the context is implied!

As for security - I can't see how this could grant the user anything they don't already have access to via the JS console and Inspect Element. All EQCSS runs on the page after it loads, so editing or adding new EQCSS styles with JS code inside `eval("")` and re-running that from the console (or waiting for an event to recompute EQCSS) seems like a more cumbersome way of running user-created JS than just entering it into the console and running it with the Enter key.

Here are some demos that make good use of `eval('')` so you can see the ways it can be used!

## [Responsive Multiline Truncation](http://codepen.io/tomhodgins/pen/KgKggX)

```
@element '[data-truncate]' {
  $this:before {
    content: 'eval("getAttribute('data-truncate').substring(0,scrollWidth/3)")…';
  }
}
```

## [Accessing value from JS in CSS](http://codepen.io/tomhodgins/pen/MKWOWW)

```
@element 'div' {
  $this:before {
    content: 'eval("coolDude")';
  }
}
@element 'aside' {
  $this:after {
    content: 'eval("new Date()")';
  }
}
@element 'span' {
  $this:before {
    content: 'Your viewport is: eval("window.innerWidth")';
  }
}
@element 'article' {
  $this:after {
    content: 'eval("addTen(5)")';
  }
}
```

## [Responsive Aspect Ratio](http://codepen.io/tomhodgins/pen/XKJpYr)

```
@element '[data-ratio]' {
  $this {
    height: eval('clientWidth * parseInt(getAttribute("data-ratio").split(":")[1]) / parseInt(getAttribute("data-ratio").split(":")[0])')px;
  }
}
```

## [Self-Responsive Social Buttons](http://codepen.io/tomhodgins/pen/Kgowak)

```
@element '[data-social] a' {
  $this {
    width: calc(eval('100 / parentNode.children.length')% - .5em + eval('.5 / parentNode.children.length')em);
  }
}
```

## [Min-font-size & Max-font-size](http://codepen.io/tomhodgins/pen/bZxvjg)

```
@element '[data-min-font],[data-max-font]' {
  $this {
    font-size: eval('
      var vw = innerWidth/100*10, /* equal to 10vw */
          min = getAttribute("data-min-font"),
          max = getAttribute("data-max-font");
      if (min !== null && max !== null) {
        vw <= min ? min : max <= vw ? max : vw
      } else if (min !== null) {
        vw <= min ? min : vw;
      } else if (max !== null) {
        max <= vw ? max : vw;
      }
    ')px;
  }
}
```

## [Number Clamp](http://codepen.io/tomhodgins/pen/ALWaVr)

```
@element 'p' {
  $this {
    font-size: eval("clamp(10,innerWidth/40,20)")px;
  }
}
```

## [Magic Min-Height Footer](http://codepen.io/tomhodgins/pen/RrEpjo)

```
@element 'body' {
  $this {
    max-width: none;
    padding: eval("querySelector('.mf-header').clientHeight")px 0 0 0;
  }
  $root,
  $this,
  main {
    min-height: calc(100vh - eval("querySelector('.mf-header').clientHeight")px - eval("querySelector('.mf-footer').clientHeight")px);
  }
}
```

## [Scroll-triggered Blocker](http://codepen.io/tomhodgins/pen/KVzePP)

```
@element 'html,body' and (min-scroll-y: 50%) {
  eval("
    var modal = document.querySelector('[data-blocker]');
    modal.style.opacity = 1;
    modal.style.pointerEvents = 'all';
  ")
}
```

## [Counting Children](http://codepen.io/tomhodgins/pen/qbrZgZ)

```
@element 'li' {
  $this {
    width: calc(100% / eval("parentNode.children.length") );
  }
}
```

## [Using HEXA colors in CSS](http://codepen.io/tomhodgins/pen/VarEPO)

```
@element 'body' {
  $this {
    background: rgba(eval("hex2rgb('#0cf')"),.2);
  }
}
```

## [Manipulating Selector Lists in CSS](http://codepen.io/tomhodgins/pen/KgwVOR)

```
eval("action('hover',buttonish)") {
  color: white;
  background-color: #999;
}
```

## [Magic Button Box](http://codepen.io/tomhodgins/pen/pbObYL?editors=1100)

```
@element '.magicButton' {
  @media (min-width: 600px) {
    $this.magicButton {
      padding-bottom: calc( eval("querySelector('button').offsetHeight")px + 30px);
      height: eval("
        var group = [],
            element = document.querySelectorAll('.'+className);
        for(var i=0;i<element.length;i++){
          element[i].style.height = 'auto';
          group.push(element[i].offsetHeight)
        }
        for(var i=0;i<element.length;i++){
          element[i].style.height = '';
        }
        Math.max.apply(Math,group)
      ")px;
    }
  }
}
```

## [Element Orientation](http://codepen.io/tomhodgins/pen/XjEZpW)

```
@element 'div' {
  $this {
    color: black;
    margin: 1em;
    background: eval("
      orient($it)=='square' ? 'blue'
      : orient($it)=='portrait' ? 'red'
      : 'lime'
    ")
  }
}
```

So there's a number of demos that feature `eval("")` in some way, some as functions embedded in CSS, some as one-liners, some using variables, some running functions stored in JS. The output of `eval("")` I've likewise used as CSS property values, selectors, and to power things like the numbers inside of `:nth-of-type()` formulas. It's a lot of fun, but so far I haven't run across any way that this could pose a security risk.

**Comment by dariuszsikorski** [comment]
Thank you for such detailed answer! I think the `eval('')` name is actually correct, since it can evaluate some js code, not only `get('')` the values. Good to hear that it won't cause security issues. The only suspicious way i can think of is nesting the eval implementation inside another scope... and this scope would contain values or methods not available outside, but... it's still only browser side after all. 

Examples are useful too, knowing how to use `eval('')` is one thing and having creative usage  is another. I can think of following usage:
- HUSL color space implementation,
- inline styling for pseudo selectors,
- adding audio to elements / interractions,
- api based styling, such as icons for battery api,
- setting properties based on ajax request: weather based themes,
- ...and curiosal implementation of polyfills, like `width: eval(" rem(10) ");` .

Modernizr list of features may be useful to get some more ideas https://modernizr.com/download?setclasses .

Thanks for the effort you bring here once again!

**Comment by tomhodgins** [comment]
Yes! Those are fantastic ideas 😊

Ever since `eval("")` was added to EQCSS it's allowed us to 'dogfood' development of new features for EQCSS instead of having to build standalone prototypes in JS too. I can mock up support for a new feature in an ugly way using JS inside CSS with `eval("")` instead of having to come up with a standalone demo to test things out.

Suppose for example I wanted to eventually support something like `(min-turtle: 3)` that applied a rule based on how many times the word 'turtle' appeared in the innerHTML of an element.

Before trying to build a `(min-turtle: 3)` polyfill or demo from scratch, or trying to figure out how to extend EQCSS to support that, I would build a little demo like this:

``` html
<p>Turtle</p>
<p>Turtle turtle</p>
<p>Turtle turtle turtle</p>
<p>Turtle turtle turtle turtle</p>
<p>Turtle turtle turtle turtle turtle</p>
<style>
  @element 'p' {
    $this {
      color: eval("
        var word = new RegExp('turtle','gi');
        var limit = 3;
        var counted = 0;
        var total = innerHTML.replace(word,function(){counted++});
        limit < counted ? 'red' : 'inherit';
      ");
    }
  }
</style>
<script src=http://elementqueries.com/EQCSS.js></script>
```

This contains the logic that a feature like `(min-turtle:)` would need, but you'd have to repeat this block of code for each property on each element you were changing when the condition applied (an element query but not a container query). One step beyond that would be isolating the logic into a helper function that could be run from CSS via EQCSS, so the three key things we need here are a term to search for, the limit, and the value to apply if the test passes. This could probably be written as a JS function on the page that could be accessed from inside any element query with something like `eval("minWord('turtle',3,'red')")`, which would run a function like `minWord(string,limit,style)` which returned 'red' or nothing.

So it's pretty flexible, and a lot of things that I used to think maybe we'd want to add to EQCSS in the future simply don't need to be added to EQCSS to be used, it's almost like you can write plugins for CSS with JavaScript, except it's most like the boundary between them has been blurred entirely where you want it to be.

**Comment by dariuszsikorski** [comment]
I played some with `eval('')`', `eq_this` and `$it` keyword to target only current element. When I resize only one element, all the `@element`'s react. Here's the demo: http://codepen.io/antraxis/pen/WGKJJA , think it works like `EQCSS.apply()` no matter which element triggers this. Is there a way to limit apply only to current element? This would be noticeable performance optimization. 

Some thoughts on nesting js in css files: Personally I like nesting js functionality in js files more. Maybe adding css property like `eval: "someJsFunction($it)";` would be even more minimalistic, just an idea though.

**Comment by jcappell** [comment]
Normally, if you trust an outside source for css, e.g. https://fonts.googleapis.com/css?family=Open+Sans, you're trusting them only for CSS, not anything that could change anything more than presentation. This insertion of scripting into CSS does open a hole of sorts. There's a reason Content Security Policy headers can have different script-src and style-src directives. This obliterates that distinction. dariuszsikorski's angle regarding comparing this to console didn't really make sense -- as you say, a client can fiddle with things on the client side already. But there _is_ an issue here of mixing scripts into css in a way that isn't usually taken into consideration. It makes it possible to seriously attack a site if you can compromise a site hosting some linked outside css.

**Comment by tomhodgins** [comment]
> This insertion of scripting into CSS does open a hole of sorts.
> …
> It makes it possible to seriously attack a site if you can compromise a site hosting some linked outside css.

Are you able to build an example that demonstrates this?

- If you include the EQCSS plugin on your website,
- _and_ you're loading CSS hosted on domains you don't control,
- _and_ you're worried that the host of this CSS may add malicious EQCSS-powered styles…

Then you can add `data-eqcss-read="true"` to any `<style>` or `<link>` tag linking to stylesheets you don't control that you know you want the EQCSS.js plugin to ignore. If the EQCSS.js plugin isn't fetching the content of those stylesheets, the non-standard syntax will be ignored and dropped by the browser when it loads it normally as CSS—and EQCSS.js won't even see it—so where's the hole?

![hacked](https://user-images.githubusercontent.com/955601/30460754-cbfe7a20-9986-11e7-8d27-5a184c2dfcc4.gif)
