### ISSUE TITLE
How does looping work in EQCSS?

### ISSUE THREAD

**Issue by baljeetrathi** [eqcss/eqcss#41]
The following code does not look like a loop:

```css
@element '.selector' and (min‐width: 500px) {
  $this {
    width: 300px;
  }
}
```

It seems that `min-width` should be replaced by `max-width` instead. But that still doesn't seem to be a loop because EQCSS recalculates styles only during page reload and window resize. Therefore, the style should be computed only once. Am I missing something?

**Comment by tomhodgins** [comment]
Hi baljeetrathi! I'm not quite sure I understand the issue you are having - is this code not doing something you expect?  It would be hard to help you out without a full test case with HTML and styles present so I can see what's happening, and what other styles might affect the same element.

In situations using EQCSS where two 'conflicting' style affects the same element, it is processed in the order they are written in the stylesheet (just like regular CSS). EQCSS is read top-to-bottom, so whatever comes last applies after everything above it haa been applied.

Also, note that EQCSS does compute on load and window resize, and also other events like scroll and input as well - this makes it useful for things like counting characters as a user types into an input or textarea, or scroll-based styling! 

Let me know if there's a specific part of code where EQCSS isn't working for you. In my experience it IS possible to make a loop, but you usually have to try to think up a situation where it could occur - so far it hasn't been a roadblock or a problem I have had when writing styles with EQCSS :D

**Comment by baljeetrathi** [comment]
Hey tomhogins,

Thanks for the prompt reply. :)

I am talking about the section titled "The danger zone!" in your article [here](https://www.smashingmagazine.com/2016/07/how-i-ended-up-with-element-queries-and-how-you-can-use-them-today/). There is a code snippet in that section:

``` css
@element '.widget' and (min‐width: 300px) {
  $this {
    width: 200px;
  }
}
```

and below that, you explain that in addition to one style continually triggering itself, there’s also the possibility of writing multiple queries that trigger each other, in what we call a “double-inverted reciprocal loop,”. I was confused about how the snippet above alone is triggering a loop. It seems to me that either `min-width` should be replaced by `max-width` or there has be something else that keeps setting the width of the widget to a value larger than 300px. Additionally, there should be something that keeps triggering the recalculation :)

Thanks for working on this plugin, it is pretty amazing!

**Comment by tomhodgins** [comment]
Hi! So in the article, the first looping example is simply an element setting the value that the condition measures. Watching min-width or max-width and then setting a width, or using min-height or max-height to set a height on the same element.

The second example would be a loop where two different queries are fighting over which rule to apply because they both want to set the same property to different values at the same time!

**Comment by baljeetrathi** [comment]
@tomhodgins  I am sorry but I just need a little more clarification. :)

``` css
@element '.widget' and (min‐width: 300px) {
  $this {
    width: 200px;
  }
}
```

As far as I can tell, the code checks if the width of the widget is at least 300px in which case it will set the width to 200px and that would be it. Now, the plugin would keep checking if the width of the widget is greater than 300px every time the window resizes or the user scrolls but how does that turn this specific part of code in an infinite loop? I wanted to get more clarification about "one style continually triggering itself". How is this part of code continually triggering itself? 

Thanks.

**Comment by baljeetrathi** [comment]
@tomhodgins Could you please clarify it for me? :)

**Comment by tomhodgins** [comment]
Hi @baljeetrathi! Its hard to explain if you don't see it from the article or code samples. The reason I can't build a demo to illustrate it in action is because we fixed this in our implementation so it resolves and picks a winner and doesn't get stuck in a loop!

I'd encourage you to play around with EQCSS and try writing some styles with it. I have been using EQCSS for almost 2 years now and so far I've run into 0 looping problems, so its not something you need to worry about unless you are writing your own element queries plugin :)
