### ISSUE TITLE
Avoid writing *-parent *-prev *-next as attributes into HTML

### ISSUE THREAD

**Issue by kaljak** [eqcss/eqcss#45]
Is there any possibility to avoid writing *-parent *-prev *-next as attributes into HTML? I am not using these meta-selectors and I don't want to have these to uglify my HTML :)

Thanks in advance

**Comment by tomhodgins** [comment]
Hi @kaljak, thanks for checking out EQCSS. These attributes are applied dynamically at the time EQCSS runs so they shouldn't be present in your HTML, only in the DOM in-browser.

There's no way that I can think of to block these from being generated and set, except linking to an older version of EQCSS that only contains `$parent` like v1.0.0: https://cdnjs.cloudflare.com/ajax/libs/eqcss/1.0.0/EQCSS.js

But you'd be missing out on a lot of other features and browser support that's been added since then!

The only place those data attributes for `prev` and `next` should ever appear should be in Inspect Element on the rendered page.

Does this answer your question?
