### ISSUE TITLE
EQCSS and ember transitions

### ISSUE THREAD

**Issue by scooterlord** [eqcss/eqcss#47]
Hello, it's me again! Hope you missed me! I am not sure that this is an element queries issue, but here goes..

We just tried implementing element queries on ember and run into the following issue. I am not sure if I can describe it properly.

Ember is using a component that relies on the width of a container that relies on element queries.

Although when refreshing or giving a direct link the element queries run properly, when transitioning within the application, the component loads earlier than the element queries - so they end up with 0 width.

...element queries are not immediately run after the transition and I noticed there is some kind of 'lazy' technique in your code. Could this be the issue?

Sorry, I hope what I am saying makes sense! :/

**Comment by tomhodgins** [comment]
Hi @scooterlord!

The 'lazy' technique in the code I think you're referring to is the [EQCSS.throttle()](https://github.com/eqcss/eqcss/blob/gh-pages/EQCSS.js#L887) function which ensures the styles are not recalculated more frequently than every 200ms.

You are able to bypass this wait time by invoking `EQCSS.apply()` manually from JavaScript at any time to trigger an instant recalculation of the rules!

**Comment by scooterlord** [comment]
Does this have to do with the initial application of the script?

**Comment by tomhodgins** [comment]
What version are you using? It shouldn't have anything to do with the initial application.

If your component non-existent in the DOM when the page first loads? Do you have a test case or code demonstrating what you're seeing online anywhere?

If clicking a button added an element to the page, and then animated it - you could call `EQCSS.apply()` right after clicking the button and adding it to the page to ensure that the styles that should apply to it _do_ apply to it right away :D

**Comment by scooterlord** [comment]
Hm, if you run Ember.apply() it seems to be working. Is there an way to disable throttling? 

edit: if it's easy to disable it when it initially runs that is

**Comment by tomhodgins** [comment]
Try `EQCSS.apply()` rather than `Ember.apply()`. I don't use Ember and am not sure what it has available but you want to trigger an EQCSS recalculation.

There's no way to disable throttling, other than modifying the EQCSS.js plugin to replace `EQCSS.throttle()` with `EQCSS.apply()` in the code that listens to events. From [here](https://github.com/eqcss/eqcss/blob/gh-pages/EQCSS.js#L904) down to the bottom of the file are where all of the event listeners are added for `EQCSS.throttle()`

But, any version of EQCSS before [v1.2.0](https://github.com/eqcss/eqcss/releases/tag/v1.2.0) will use `EQCSS.apply()` directly (though other features may be missing). The throttle was something we had to add to answer a change made in Firefox that led to too many recalculations, so we had to find a way to limit it so it didn't recalculate automatically more frequently than it needed to.

Do you have a test case of this online anywhere? It's hard to troubleshoot without seeing what's happening!

**Comment by scooterlord** [comment]
Sorry I meant EQCSS.apply()! let me check and get back to you

**Comment by scooterlord** [comment]
...so, I changed all throttle() with apply() and we get some really strange behaviour.

In Firefox and IE 11, we are getting the expected behavior. After a transition, soft browser reload or hard reload, EQCSS run properly.

However, in Chrome we get a strange behavior. After transition or hard reload (ctrl-f5) EQCSS runs properly. However, if you do a soft browser reload (f5), EQCSS runs only after CLICKING on the browser. I have no idea why this happens - I get no errors in the console. Does it ring any bells on your end?

**Comment by tomhodgins** [comment]
What version of EQCSS are you using? There was an issue similar to that I saw and fixed that had to do with the order things loaded in, but that fix came out in [v1.3.1](https://github.com/eqcss/eqcss/releases/tag/v1.3.1) all any version beyond that should be good.

It's going to be hard for me to troubleshoot or suggest things unless I have the following information:

- version of EQCSS you're using
- either the code you're using that isn't working, or a test case that reproduces the same error

Without those I can only guess as to what you might be seeing, and I'm totally unable to test any fixes!

**Comment by scooterlord** [comment]
I am using EQCSS 1.4.0. A test case is really hard to reproduce at this point, but if a solution is not found I will try to do it in the near future so that we can potentially help others with the same issues.

We aren't running something strange. A css file with the contained element queries is loaded, EQCSS with the alterations throttle() replaced with apply().

What is really strange is that the element queries are loaded AFTER you click anywhere in the DOM. And it is also stranger since it loads in Ember transitions and hard reload but not soft reload. In the next few days I will try to isolate the issue, stripping code. Unfortunately I am working overtimes at this point, but as soon as a chance is given I will get back to you. In case something comes up in your mind, please share.

edit: I stripped all code except the EQCSS and the necessary code (it's d3.js) to run the widgets into the element container. I also tried putting the css inline. Nothing, still the same behavior..

**Comment by tomhodgins** [comment]
Hey @scooterlord! Here's a small test case I have built to see if I can reproduce what you're seeing.

In each demo there is a button that adds a new `div` element to the page after a 1 second delay. Does this imitate what you are doing adding your component?

I with my first broken demo by putting all of my styles inside of an `@element` query. The styles inside this use things like `ew` units, which means the element must have a width already before that can be computed, and since the width is also being applied by the `@element` query we definitely won't see anything before EQCSS applies.

```html
<input type=button onclick="
  setTimeout(function(){
    document.body.innerHTML+='<div></div>';
  },1000)
" value=Add>

<style>
  @element 'div' {
    $this {
      width: 100%;
      height: 100ew;
      border-radius: 100%;
      background: red;
    }
  }
</style>

<script src=http://elementqueries.com/EQCSS.js></script>
```

Every time you click the button here is the chain of events that is happening:

- click event triggers `EQCSS.throttle`
- mouseup event triggers `EQCSS.throttle`
- `EQCSS.throttle` fires after `200ms` delay
- `800ms` later a `div` element is added to the page (`1000ms` after initial click event)

The result of this is that unless `EQCSS.apply` is triggered by JavaScript _after_ the new element is added to the page, we have to wait for the next event (click, input, resize, etc) to trigger an EQCSS recalculation before we will see our new element.

But…if we were to lower the timeout, and add our object to the page _faster_ than `200ms` after the click event, we _would_ see it show up as it should, because our order of events would look like this:

- click event triggers `EQCSS.throttle`
- mouseup event triggers `EQCSS.throttle`
- `100ms` later the `div` added to the page
- `100ms` after that, `EQCSS.throttle` has `EQCSS.apply` recalculate styles

```html
<input type=button onclick="
  setTimeout(function(){
    document.body.innerHTML+='<div></div>';
  },100)
" value=Add>

<style>
  @element 'div' {
    $this {
      width: 100%;
      height: 100ew;
      border-radius: 100%;
      background: red;
    }
  }
</style>

<script src=http://elementqueries.com/EQCSS.js></script>
```

So how can we style things that show up after `200ms`, the `EQCSS.throttle()` timeout? There are a couple ways you can help it. In this next demo I've created a CSS fallback for the EQCSS-powered styles. This way _something_ will show up, before being corrected by EQCSS when it runs:

```html
<input type=button onclick="
  setTimeout(function(){
    document.body.innerHTML+='<div></div>';
  },1000)
" value=Add>

<style>
  div {
    width: 100%;
    height: 100%;
    border-radius: 100%;
    background: red;
  }
  @element 'div' {
    $this {
      height: 100ew;
    }
  }
</style>

<script src=http://elementqueries.com/EQCSS.js></script>
```

But as you can see, this isn't a complete solution - since the styles powered by EQCSS are likely key styles (or else you wouldn't be using it for that). So another way to work around this would be to trigger EQCSS after the animation (or addition in this case) is complete by running `EQCSS.apply` from JavaScript when you know it should be recalculated:

```html
<input type=button onclick="
  setTimeout(function(){
    document.body.innerHTML+='<div></div>';
    EQCSS.apply();
  },1000)
" value=Add>

<style>
  div {
    width: 100%;
    height: 100%;
    border-radius: 100%;
    background: red;
  }
  @element 'div' {
    $this {
      height: 100ew;
    }
  }
</style>

<script src=http://elementqueries.com/EQCSS.js></script>
```

This fixes what we see entirely - for me. If you have a way that you can run `EQCSS.apply` after you know the transition is complete you should be okay.

I'm going to do a couple of other examples where you might want to rig up EQCSS for a smooth transition. Have you ever used requestAnimationFrame?

Here's a demo where I have an element with EQCSS-powered styles that calculate the height based on the element's width. When you click the button it will animate adding `50px` to the current width over the course of 2 seconds. To animate this I've used `requestAnimationFrame` and the HTML5 performance API to measure 2 seconds, and for the `2000ms` that the function loops, EQCSS is applied continuously - but after the animation is complete, it stops being recalculated.

```html
<input type=button onclick="setup()" value=animate>
<div></div>
<style>
  @element 'div' {
    $this {
      margin: 1em;
      width: 50px;
      height: 100ew;
      background: lime;
    }
  }
</style>
<script>
  var start
  var elapsed
  var duration
  var origWidth
  var div = document.querySelector('div')

  function setup(){
    start = performance.now()
    elapsed = 0
    duration = 2000
    origWidth = div.offsetWidth
    window.requestAnimationFrame(animation)
  }
  function animation(){
    if (elapsed < duration) {
      elapsed = performance.now() - start
      div.style.width = origWidth + (50/duration)*elapsed + 'px'
      EQCSS.apply()
      window.requestAnimationFrame(animation)
    }

  }
</script>
<script src=http://elementqueries.com/EQCSS.js></script>
```

And here's a link to the same demo on Codepen: http://codepen.io/tomhodgins/pen/VmqNgE

Here's another example - maybe this is how your animations are broken. Here we have a button that adds an `.active` class to an element and the width is animated over `2s` using a CSS transition, and we also have a height powered by an EQCSS style. By default, the animation won't be very smooth:

```html
<input type=button value=toggle onclick="
  var div = document.querySelector('div')
  div.classList.toggle('active')
">
<div></div>
<style>
  div {
    width: 50px;
    background: lime;
    transition: width 2s ease-in-out;
  }
  .active {
    width: 200px;
  }
  @element 'div' {
    $this {
      height: 100ew;
    }
  }
</style>
<script src=http://elementqueries.com/EQCSS.js></script>
```

I think this is maybe what you're talking about.

Perhaps you need to continuously recalculate EQCSS for a specified duration of time. Could you make a helper function in JavaScript that takes a given duration (in ms) that you want to recalculate EQCSS for, and run that at the same time any animations are triggered? Here I've added `requestAnimationFrame(animation.go(2000))` that runs at the same time our class gets added and is uses the function in the `animation` object down below.

```html
<input type=button value=toggle onclick="
  var div = document.querySelector('div')
  div.classList.toggle('active')
  animation.duration = 2000
  requestAnimationFrame(animation.go)
">
<div></div>
<style>
  div {
    width: 50px;
    background: lime;
    transition: width 2s ease-in-out;
  }
  .active {
    width: 200px;
  }
  @element 'div' {
    $this {
      height: 100ew;
    }
  }
</style>
<script>
  var animation = {
    start: 0,
    duration: 2000,
    active: false,
    go: function(){
      if (animation.active == false){
        animation.start = performance.now()
        animation.active = true
      }
      var elapsed = Math.floor(performance.now() - animation.start)
      if (elapsed < animation.duration) {
        EQCSS.apply()
        console.log(1)
        requestAnimationFrame(animation.go)
      } else {
        animation.active = false
      }
    }
  }
</script>
<script src=http://elementqueries.com/EQCSS.js></script>
```

Here we have a function, `animation.go()` that will continuously run `EQCSS.apply()` for `2000ms` by default, or whatever duration we give it.

Here's a link to a demo with a choppy and smooth toggle: http://codepen.io/tomhodgins/pen/gLZJwO/

You might be able to use a function like this to run EQCSS for a period of time after triggering any animation via CSS or other means on your website. I hope this helps point you in the right direction, or at least inspire some solutions you can try.

Here's an animation: of the last two demos: https://i.imgur.com/dnxAaDZ.gif

Let me know how you make out, and if any of these examples illustrate what you're seeing.

**Comment by scooterlord** [comment]
Hello again Tom and thank you for getting into the trouble not only for just helping me, but also spending so much time to please me! Sorry it took me so long to respond, but I am in a 3-day workshop and haven't been able to answer earlier.

To quote:

> The result of this is that unless EQCSS.apply is triggered by JavaScript after the new element is added to the page, we have to wait for the next event (**click, input, resize, etc)** to trigger an EQCSS recalculation before we will see our new element.

The bold part answer the question as to why the layout was corrected AFTER a click - I had no idea it was bound to click events as well - it was very curious behavior so now that I realize this we are getting somewhere.

We are about to release a framework within our company that was using EQCSS. The problem is that multiple teams within the company work with different front-end frameworks - ember, angular, react, whatever. My team is using Ember - after using your previous suggestion, I replaced the throttle() function with apply() function but we still didn't get the right results - but this would happen on Chrome only. I guess it has to do with the way the Javascript is handled between browsers. In Ember, JS being loaded async, all the Javascript scripts are running in parallel and are 'racing' towards which script will load first - so in Ember and using our widget scripts, looks like the widgets JS loads first.

I had already ended up in using one of your suggestions above, before you replied - I added a EQCSS.apply() function, right before rendering the widgets, however, this is considered unacceptable by developers - and unfortunately I have to agree with them; it's really bad practice to 'hardcode' additional JS just for layout purposes. Let alone it doesn't inspire confidence that it would work in different front-end frameworks, so I personally wouldn't risk having to troubleshoot the plugin in every front-end framework currently used, or MIGHT be used in the future.

Obviously, this has nothing to do with the excellent work you have done with the plugin (and shared with us! :) The unfortunate thing is, that I might have to create custom css to cover all scenarios that would be instantly covered by your plugin - that is.. hardcoding a custom 12grid in parts, with or without left sidebar, with or without right sidebar... as you can realize your plugin was heavenly when I first met, used and tested in my layouts, but unfortunately unexpected limitations might not allow us to use it... :/

Edit: recalculating for a fixed period of time might not cut it also. Although 2000ms is a fairly long amount of time, it might still not be enough for anything to render all widgets in a page.

Additionally, there isn't any animation issue per se, but from what I realize from your examples above, using requestAnimationFrame might not lead to performance issues if the script is being run simultaneously with the rendering or loading of other JS elements?

It's 2am right now, after a long day, and don't have energy to reproduce the issue since we have changed the code, not even in Photoshop. However, picture this (until I provide screenshots sometime tomorrow if I don't get the message accross). We are using d3.js that renders various svg elements that are bound to their container's size - a widget. The widget gets it width based on an element query that is based on its parent widget-container element. If the d3.js code runs BEFORE the eqcss element query is applied, then the widget has no width and renders without width.

**Comment by tomhodgins** [comment]
Oh no! I was trying to find a way I could package up the plugin in a modular way that would satisfy webpack, node, etc - without preventing it from being loaded globally in the browser by itself if no module loader is present - here's my WIP: http://staticresource.com/webpack-demo/node_modules/eqcss/EQCSS.js

I'd also like to expose the `EQCSS.apply()` and `EQCSS.throttle()` functions in a way that would allow them to be used from within these sorts of workflows when used as a module, but I'm still waiting to hear back from a friend about how to do that. Do you know how EQCSS could be packaged up in a way that these functions could be used from inside any other module you're writing?

Could changes like the link above help satisfy some of the rough edges you're finding when trying to use it from within your workflows and tools?

I've also begun work on an EQCSS to JavaScript compiler that would read styles written in EQCSS syntax and output 100% vanilla JavaScript that could be included with a page and to do the same thing without needing the EQCSS or EQCSS plugin present. Work is still just starting on it, but perhaps this workflow could be a way people could author EQCSS syntax when writing solutions even if they aren't using EQCSS in the browser? I don't see how EQCSS could be 'flattened' to CSS alone, but maybe it could be exported entirely to Javascript. The compiler repository is located here: https://github.com/tomhodgins/eqcss-compiler

Let me know if there's anything I can do to make it easier for you to work with :D

**Comment by scooterlord** [comment]
Tom, man, are you waiting for me to ask so that you can immediately answer? :) +1

Even if a module existed it wouldn't help us in our case scenario. We are trying to be 'dependency free' - meaning, just load a js file that handles everything auto-magically. Adding an extra module is a no-go for OUR use case.

Obviously as I said before, it would definitely work if it was used in just one specific application, but it's a huge risk to be used in multiple unknown to us front-end frameworks.

What you commented above would be the best case scenario for our case. **Have the plugin somehow 'compile' css after it was being fed with a set of queries and conditions.**

I really hope that the specifications you are working on are accepted and enter the next CSS version, but even so - it would still take a long time until it would be widely supported by the majority of devices so that you could safely support it.

edit: once more a big thank you for your efforts to provide not just to me but to the whole community! Off to sleep I can barely keep my eyes open!

**Comment by tomhodgins** [comment]
Hey @scooterlord haha I just happened to be sitting here and working on related stuff :D

> meaning, just load a js file that handles everything auto-magically

It was originally intended to be run like a shim or polyfill, something like Typekit's JS file that gets added to your HTML once and you're ready to go - is that what you're meaning?

Most of the times I'm using it I'm either linking to the current latest version, or a specific version hosted on CDNjs like this:

```
<script src=//elementqueries.com/EQCSS.min.js></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/eqcss/1.4.0/EQCSS.min.js"></script>
```

> it's a huge risk to be used in multiple unknown to us front-end frameworks.

It should behave the same way with all frameworks and tools, it runs in the browser environment, not as JS in the server environment. As long as it's included in the HTML of the page, it shouldn't matter what tools you use to build your HTML. I do find it strange that some of these frameworks make it hard to access global functions to trigger something like `EQCSS.apply()`, but sometimes they will allow something like `window.EQCSS.apply()` from within their modules to reach the plugin.

> I really hope that the specifications you are working on are accepted and enter the next CSS version, but even so - it would still take a long time until it would be widely supported by the majority of devices so that you could safely support it.

Thanks! I also feel like this will building using these concepts will require plugins to interpret, or at the least compiling another syntax into JavaScript, for a number of years to come! I'm not sure if they'll ever be included in CSS proper, but I'm really looking forward to being able to write 'browser plugins' instead of web-based plugins in the future with things like Houdini. Hopefully the stuff we're doing here is a good candidate for that sort of functionality and we run this kind of logic much closer to the browser than to the HTML or apps running on top of that.

Hope you had fun playing around with EQCSS, sorry for any frustration it has caused, and keep an eye on where it grows. I'm dedicated to improving this whole area of responsive design and so I intend to keep hacking away at different solutions until the best way to do this stuff is found!

Perhaps there's another way you could implement a simpler width and height-based query plugin within your company framework! If you just need a few conditions, and only to support pixels as a unit, it can take as few as [~35-40 lines of JavaScript](http://codepen.io/tomhodgins/pen/bwwNRr) to get a simpler version of element queries working! It should be easy enough to whip something up in-house that will do everything you need and still save you having to write all those layout-dependent `@media` queries.

**Comment by scooterlord** [comment]
Thanks for your reply once more. Although you must have already realized it, it's an US issue and not a YOU issue. Although the needed effect can be achieved by adding some additional JS, we still have a limitation concerning how it is issued and what external dependencies are used.

As I said above, having a compiler that exports CSS would be the best for our case - meaning, export CSS by inputting element queries somehow. I can give it some thought later and get back with ideas if you are willing to help! Concerning what you said, percentages and ems are used in our code for the best browser support. Edit: Only using CSS would be the best case scenario when dealing with JS front-end frameworks to inspire confidence it will be used anywhere without additional code - which either way will have to be written, either with the help of your plugin or manually! :/

And no, it hasn't caused any frustration, dont worry about it. It's how development is - always fun! :)
