### ISSUE TITLE
LESS compile @element condition problem

### ISSUE THREAD

**Issue by gabormeszoly** [eqcss/eqcss#48]
Any solution this problem? `@breakpoint-sm` variable is not compiled.
Thanks!

```
@breakpoint-sm: 400px;

@element '.column' and (min-width: @breakpoint-sm) {
  eq_this h2 {
    color: red;
  }
}

**Comment by tomhodgins** [comment]
Hi @gabormeszoly! Thanks for checking out EQCSS. I have played around with Less a little bit and it looks like the part it's not liking is the `@element`, since it believes it to be an unsupported 'directive' in Less.

Are you able to add support for custom 'directives' in Less yourself, or would this only be able to be fixed if the Less project added support for `@element` query syntax?

Does Less allow you to write a block of code that it passes through untouched? In the past SASS users have come up with the following mixin: https://gist.github.com/thejase/d2107285b6e10315dd6bc055115647fe

Could an approach like this work for Less too?

Alternatively, if you're trying to get EQCSS code working and it's not playing well with your Less files, your options for including EQCSS are:

- in a separate .css file not watched by Less and loaded into the site normally
- loaded in a file like `styles.eqcss` file, linked into the site with a script tag with custom type: `<script src=styles.eqcss type=text/eqcss></script>`

I really hope you can get this working! I'll keep tinkering around with the Less syntax to see if I can convince it to work. Let me know if you get it working as well!

Hope you're having a great day,
Tommy

**Comment by tomhodgins** [comment]
The Less docs say: http://lesscss.org/functions/#string-functions-e

>## e
>>CSS escaping, replaced with `~"value"` syntax.
>
> It expects string as a parameter and return its content as is, but without quotes. It can be used to output CSS value which is either not valid CSS syntax, or uses proprietary syntax which Less doesn't recognize.

But I can't seem to get it to escape the whole rule. Perhaps something like that is part of the solution though!

**Comment by gabormeszoly** [comment]
Thanks @tomhodgins i'll try to write a less mixin, like this: https://gist.github.com/thejase/d2107285b6e10315dd6bc055115647fe

**Comment by hrobertson** [comment]
@gabormeszoly Did you make any progress on this issue?
Thanks

**Comment by kennymalac** [comment]
@hrobertson 
I got it working by doing this, as described in https://github.com/SomMeri/less4j/wiki/Less-Language-Selector-Interpolation

```less
@elemQuery: ~"@element .example and (max-width: 767px)";

@{elemQuery} {
...
}
```
