### ISSUE TITLE
Idea: Plugin Support

### ISSUE THREAD

**Issue by alflennik** [eqcss/eqcss#50]
First of all, this project is so cool it hurts. I had no idea this was possible and I LOVE it. So many wins.

I was thinking about the eval() addition and the ew, eh, emin elements, and, well, I think the setup you have for dynamically altering CSS could allow for some EVEN MORE interesting stuff.

Plugins.

Like say using JS variables systematically and easily in your css. Or a working polyfill for CSS vars. All built on EQCSS.

I love this lib. Seriously.

**Comment by tomhodgins** [comment]
Hey @alflennik! Thanks so much :D Originally when we were building EQCSS we had a big long list of features we wanted to support - but after we added `eval("")` it's possible to add quite a bit of that functionality yourself.

The original reason we wanted to add `eval("")` was so we could use the value of a JavaScript variable anywhere in CSS. Currently CSS variables are only supported in a few browsers, but even still they are limited in what they can accomplish:

- CSS variables can be set by JS or CSS
- CSS variables can be changed by JS or in media queries
- CSS variables can be used as the `value` of any CSS property

But then there are also limitations:

- some browsers will never get CSS variables
- CSS variables cannot be used in pseudo-element `content:;` property

So when we originally created `eval("")` we were just hoping to be able to write something like `eval("someVariable")`. But since EQCSS is alive on the page I found myself wanting to use `eval("")` to find out information about the currently scoped element!

We expanded the support of what `eval("")` can to do allow you to nest large amounts of JS inline, which really opens up what you can use it for. Over time this meant that many of the features we originally wanted to support were still possible to write your own support for.

You can kind of think of `eval("")` as that way to write in individual support for something you need to use right in your CSS, it's really handy!

Here are some of my favorite uses of `eval("")` and a little bit about them!


## Using JS Variables in CSS

The first use of `eval("")` is to interpret JS variables. Already this implementation is stronger than CSS Variables as it works in all browsers IE8 and up, and doesn't share the same limitations with `content:;` as CSS Variables.

- use variables
- evaluate inline JS
- use the value returned from a function

[Using JS variables in CSS](http://codepen.io/tomhodgins/pen/MKWOWW)

Here's a basic demo where you can see CSS using values retrieved from JavaScript at the time the EQCSS applies.

[Night Mode for Websites](http://codepen.io/tomhodgins/pen/VPwGPG)

In this pen there's an orange overlay that changes its visibility based on the time of day. Something like this would be possible with CSS variables being set dynamically from JavaScript - but in this case building with EQCSS gives us better browser support.

[HSL Sliders](http://codepen.io/tomhodgins/pen/bgbpWL)

In this demo we're using `eval("")` in EQCSS to actually set some variables, which we also later use in another query. I don't think this is the best way to do this (compared to watching and updating these in JS) but it goes to show how a full round trip could work (EQCSS -> JS -> EQCSS)


## Using `eval("")` to run functions

Another fun thing I like to do when using EQCSS is write helper functions that capture a tiny big of logic and allow me to use that logic in my CSS.

[Number Clamp in EQCSS](http://codepen.io/tomhodgins/pen/ALWaVr)

You may have heard of 'CSS Locks', the idea that you could set a responsive font-size but give it a minimum & maximum number beyond which they never shrank or grew - well you fan fake `min-font-size` and `max-font-size` with a tiny function that looks like this:

```
function clamp(min,mid,max){
  return Math.min(Math.max(min, mid), max)
}
```

[HEXA Color Support](http://codepen.io/tomhodgins/pen/VarEPO)

This is another demo where we are able to use a function in JavaScript to convert a HEXA colour (#00000000) into a color format that CSS can read.



## Using `eval("")` to compute inline JS

Another cool thing `eval("")` is useful for is sticking a teeny tiny bit of logic right in your CSS. This is especially great for all those cases where normally you'd have JavaScript watching elements and toggling classes. Instead we can use `eval("")` to inline that JS logic right in the styles they apply. No need for setting classes here - we can compute the values we need based on anything!

[Auto-Expanding Textarea](http://codepen.io/tomhodgins/pen/QKdEdb)

Here a textarea expands (and contracts) to always surround the height of its contents. I wish this sort of behaviour was the default for `<textarea>`!

[Reading Quark Classes](http://codepen.io/tomhodgins/pen/ggGYZJ)

Here's a silly demonstration of EQCSS using `eval("")` to parse and apply styles based on cleverly crafted class names (that map to JavaScript style names and values)

[Overflow Shadows](http://codepen.io/tomhodgins/pen/egpmWN)

This demo uses an elements scroll position to apply styles in a direct way.


## Using `eval("")` to fake unsupported selectors

So this is where we start to take things in a direction that CSS Variables can never go! With `eval("")` you can evaluate a tiny bit of JS _anywhere_ in CSS, as long as it's inside of an element query. This means you can use `eval("")` for things CSS Variables can't do:

- use `eval("")` inside `content:;`
- use `eval("")` to help write selectors
- use `eval("")` to write new selectors
- use `eval("")` to write property names (vendor prefixing?)
- use `eval("")` to send JS information when an element query condition is met
- etc…

[Selecting Elements by Text Content](http://codepen.io/tomhodgins/pen/EZYMyK)

Here we're using `eval("")` as a way to select an element based on the text it contains.

[Faking :in-viewport](http://codepen.io/tomhodgins/pen/amKZmV)

This is more of a brainstorm than a solution. You can tell it has a little performance issue with the scrolling - but what we're doing here is running quite a bit of JS logic over some elements to determine whether they are fully visible in the viewport, or even partly visible in the viewport, and apply styles to just those elements.

This isn't the sort of solution I would use EQCSS for in production, but it's absolutely 100% the sort of solution I would use EQCSS to help me prototype and nail down the logic for before I build out the rest of a feature like this in JavaScript. In this way, `eval("")` is like a breeding ground for CSS polyfills!

[Selecting "buttonish" and "textish" elements](http://codepen.io/tomhodgins/pen/KgwVOR)

Here we're storing a big list of selectors in an array in JavaScript and using `eval("")` in CSS to refer to the entire list of selectors at once. The cool thing here is that we can also write a helper function that returns the same names with modifiers like `:hover` and `:focus` so we're able to use these selector lists to make our CSS small and legible, while still making it easy to modify that list (in all of the places it has been used) easily.

[Selecting Value Ranges](http://codepen.io/tomhodgins/pen/KaKPOJ)

This is another brainstorm - what if you could use attribute selectors to select elements based on the _range_ of values. Currently you could write `[type=range][value=50] {}` to select `<input type=range value=50>`, but you have no way of specifying values "over 50" or "less than 50". It would be cool if CSS had awareness that certain values were numbers and could be thought about as numbers. Imagine if someday we could do: `[type=range][value<50] {}`. You can use `eval("")` today to mockup these ideas and dreams.


## Using `eval("")` to fake CSS variables

Probably the most obvious use of `eval("")` is to bring CSS Variable-like functionality to all browsers. Virtually any demo that makes use of CSS Variables in newer browsers can be simply converted to EQCSS if support down to IE8 is required.


[Mouse Cursor Flashlight (CSS Variables)](http://codepen.io/tomhodgins/pen/egWjBb)

To start things off, here's a demo using CSS Variables that's fun to play around with. The X and Y coordinates are being set by JavaScript and so as you move your mouse, the location of the gradient on your screen follows.

[Mouse Cursor Flashlight (EQCSS)](http://codepen.io/tomhodgins/pen/oBWMvv)

This is the previous demo in its original form - it's doing the exact same thing so I linked these two so you could see how any CSS Variable enabled demo could be converted to EQCSS.

[Faking CSS Variables](http://codepen.io/tomhodgins/pen/WGmgdk)

Here's another very similar demo…

[Cursor based box-shadow](http://codepen.io/tomhodgins/pen/ggWMpg)

And then this brings us to a really fun demo - box-shadows based on a light source (the cursor). This is so similar to the flashlight demo you might be tempted that it's possible to build with CSS Variables, but this is the perfect use case to see the limitations of CSS Variables compared to…JS. In this demo we're able to use a teeny tiny bit of JS in our CSS styles _with_ the mouse coordinates in order to come up with the correct shadow, but if we were forced to use CSS Variables we would either need unique variables for each element (for JavaScript to compute) or else we would forgo styling this in CSS and use JS to watch the page and apply the styles it needs. By using EQCSS we can abstract away that custom JS and keep our CSS pretty small too!

---

So there are a few demos of `eval("")` that show a few different ways it can be used, and hopefully I've shown how `eval("")` can get around the limitations of CSS Variables, while replacing 100% of what they do as well!

If you're looking for further reading about `eval("")` I would check out:

- [Eval("") in the element queries spec](https://tomhodgins.github.io/element-queries-spec/element-queries.html#eval)
- [Previous Github issue about `eval("")` with more fun demos](https://github.com/eqcss/eqcss/issues/38#issuecomment-252716913)

Happy hacking!

**Comment by alflennik** [comment]
Eval support might just be the sleeping giant of this plugin. What you can
do is absolutely incredible. That's what inspires me!

The tinkerer in me wants to get my hands dirty on this! I'll give you an
example. Although it's not directly supported (as far as I know), CSS
module namespaces have been a holy grail for a long time, but no one has
been able to get around the onerous configuration problems. I want to use
class names like "name" and "title" in my HTML and CSS, and I don't want to
have to go crazy configuring it.

This is why I suggest plugins.

This lib does stuff with CSS that I had NO IDEA was possible. And all those
cool examples (especially about the JS vars) show me just how potential
there is! I really dig the detailed response. Thank you for taking the time!

**Comment by tomhodgins** [comment]
Ah glad to hear @alflennik! It's been a wild ride the past couple of years working with EQCSS - I'm really looking forward to 2017 and the fun stuff we'll discover.

I'm curious to hear more about what you mean by this:

> Although it's not directly supported (as far as I know), CSS
module namespaces have been a holy grail for a long time, but no one has
been able to get around the onerous configuration problems. I want to use
class names like "name" and "title" in my HTML and CSS, and I don't want to
have to go crazy configuring it.

When I think of CSS modules, I think of the idea of trying to introduce some kind of namespace to CSS so your CSS applies only to and element (and its children). To do this, some people were trying to use things like the [`<style contain>`](https://developer.mozilla.org/en-US/docs/Web/CSS/contain) style scoping. Some people use things like [ShadowDOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM) components, or web components for this type of scoping, and still others use tool-based solutions like [CSS Modules](https://github.com/css-modules/css-modules), [Styled Components](https://github.com/styled-components/styled-components), [Aphrodite](https://github.com/Khan/aphrodite), etc which live right inside the frameworks people are using to build sites.

A lot of these solutions work by assigning unique identifiers to your elements in HTML and applying styles to elements individually. The way we have implemented EQCSS this sort of unique identifier is not necessary! We've created out own form of style scoping which allows you to write styles that apply to an element, or an element that meets certain responsive conditions. Once you have one or more elements on the page that match that criteria you are able to assign styles from the context of that element, in effect replacing the need to give it a unique identifier. It's easy to apply styles to the [parent element of a scoped element](http://codepen.io/tomhodgins/post/a-parent-selector-for-css) (AKA a parent selector), as well.

To read more about how style scoping works, check out:

- [How Style Scoping Works with Element Queries](http://codepen.io/tomhodgins/post/how-style-scoping-works-with-element-queries)
- [Style scoping in the Element Queries spec](https://tomhodgins.github.io/element-queries-spec/element-queries.html#element-queries)

And check out the demos for `$this`, `$parent`, and `prev` as well.

You're always welcome to join us in the EQCSS chat at https://gitter.im/eqcss/eqcss too 😃💬
