### ISSUE TITLE
Error "Unable to get property 'replace' of undefined or null reference"

### ISSUE THREAD

**Issue by alex-figge-schuster** [eqcss/eqcss#72]
On IE 11 i get this JS error:
_Unable to get property 'replace' of undefined or null reference_
It's origin is in EQCSS.parse=function(code) {...}

On Safari 8 on MacOS I get a similar error.
I'm using EQCSS 1.7.0

**Comment by tomhodgins** [comment]
I've left a little comment about this on the recent PR with some debugging ideas. This is an issue that has been spotted before, but from all troubleshooting done so far it appears to be some kind of interaction between the JavaScript on those particular sites and EQCSS.js, not a problem with the queries themselves or the EQCSS.js plugin.

I'd love to be able to troubleshoot more sites where this error occurs so we can understand how to avoid it, but solutions that involve having EQCSS ignore the fact that something has gone wrong sounds like a setup for a debugging nightmare (where your tools are lying to you that things aren't broken when they are).

I left some debugging tips and ideas over the in PR that apply here as well -> https://github.com/eqcss/eqcss/pull/76#issuecomment-332918211

**Comment by hrobertson** [comment]
@tomhodgins 
Just downloaded this plugin and hit this issue right away.
In my case it's because `xhr.responseText` is not guaranteed to be defined when `xhr.onreadystatechange` function is called. So EQCSS.process is called with the argument being undefined.

Using `onload` or checking the `readyState` property would fix this issue.
However, I see in [31180f](https://github.com/eqcss/eqcss/commit/31180f98ceb00af1bade60d85dfa42be3fc1e8e1) it was changed from using `onload` to `onreadystatechange` and presumably there was a reason for that.

Alternative could be to check the validity of the argument in EQCSS.process.

**Comment by tomhodgins** [comment]
Hey @hrobertson! Thanks for your comment, I need to get a fix out for the `<style>` inside `<svg>` bug that's happening in a similar place in the code.

Are you able to elaborate on what stylesheet was being processed before it was fetched, or are you able to build a demo that reproduces this? I don't recall right now the immediate reason that was changed though I was doing a serious about of browser testing with that release and fixing some stuff for IE8 so it was likely something related to that.

**Comment by hrobertson** [comment]
Found the real issue for me - I'm working on an existing site that is using https://github.com/jpillora/xdomain which intercepts XHR requests.

[The spec](https://xhr.spec.whatwg.org/#dom-xmlhttprequest-responsetext) says responseText should be an empty string but I'm guessing xdomain is not adhering to that.

**Comment by hrobertson** [comment]
I haven't retested but this should have been fixed by this PR: https://github.com/jpillora/xhook/pull/75
