### ISSUE TITLE
Not compatible with "use strict"

### ISSUE THREAD

**Issue by magicznyleszek** [eqcss/eqcss#77]
I import eqcss inside my .ts file, and webpack ts-loader automatically adds `"use strict"` to ES6 modules. I tried configuring it to not add it, but with no luck - my workaround was to load the script as separate file, outside of webpack. But it is possible that some people will have this problem and having code working under `"use strict"` is always a fun thing, so consider changing it :-)

The error is:

```
ERROR [source-reader.karma-typescript]: Error parsing code: 'with' in strict mode (1239:8)
in (…)/node_modules/eqcss/EQCSS.js
at line 1239, column 8:

... with ($it) { ret = eval(string.slice(1, -1)) }

   ...
```

**Comment by tomhodgins** [comment]
Hi @smutnyleszek!

This is definitely something that has been pointed out before, I've included some comments around it in the file:

```javascript
/*
 * Eval('') and $it
 * (…yes with() was necessary, and eval() too!)
 */

EQCSS.tryWithEval = function(element, string) {

  var $it = element;
  var ret = '';

  try {

    with ($it) { ret = eval(string.slice(1, -1)) }

  }

  catch(e) {

    ret = '';

  }

  return ret;

}
```

I believe it might be possible to refactor `eval()` out of there, and in following plugins I have built since EQCSS I have done that, but the `with()` in EQCSS is evaluating the JavaScript from within the context of the element you're testing so to remove that would be a breaking change. (We've tried and there's no way we've found to refactor it out).

Fortunately EQCSS never _needs_ to be loaded on the backend and packed like that, it's written for `window` so you can think of more like a browser shim, or something that can be linked to directly in the browser (even CDN-hosted) since it only really works there.

In [newer plugins](https://github.com/tomhodgins/reprocss/blob/master/mixins/scoped-eval.js) I'm making I have successfully avoided both `eval()` and `with()`. Here's a 'scoped eval()' plugin for CSS using a very similar syntax as EQCSS's `eval('')` to do the exact same thing, but instead of implied context or using `$it` as a placeholder for the element, you use `this` instead:

```javascript
function scoped(selector, rule) {

  var tag = document.querySelectorAll(selector)
  var style = ''
  var count = 0

  for (var i=0; i < tag.length; i++) {

  var attr = selector.replace(/\W+/g, '')

    tag[i].setAttribute('data-scoped-' + attr, count)

    var scopedRule = rule.replace(/eval\((.*)\)/g, function(string, match){

      var func = new Function('return ' + match)

      return (func.call(tag[i]) || '')

    })

    style += '\n/* Scope: ' + selector + ' */\n'
             + '[data-scoped-' + attr + '="' + count + '"] {\n'
             + '  ' + scopedRule + '\n'
             + '}\n'

      count++

  }

  return style

}
```

Here the `eval()` in JS is being replaced by `var func = new Function('return ' + match)` and the `with()`-like functionality in JS is coming from the `call(tag[i])` part of `func.call(tag[i])`. If you are looking to build your own plugin, or make a custom build of EQCSS that you don't mind being different from the normal plugin I would recommend doing it this way and using `this` inside your evaluated code to represent the element you are testing instead, here's an example of how you'd use this mixin:

```javascript
scoped('div', `
  margin: 1em;
  background: lime;
  height: eval(this.offsetWidth / (16/9))px;
`)}
```

So you can see the syntax is very close to EQCSS but using `this` instead. I'm open to suggestions if you can find a way to refactor `with()` out of EQCSS without making a breaking change to what's already working, but otherwise I think it's ok as it is :D

**Comment by magicznyleszek** [comment]
Yeah, you're right. Let's close this :-)

**Comment by lagden** [comment]
Humm...
I have the same problem!

```shelll
SyntaxError: 'with' in strict mode (1304:8)
```

I don't know all context, but I think is possible make it using `new Function` instead `eval`.
And didn't know about `with` in js. I used a lot in as3 (action script3 - Flash).

**Example:**

```js
function _conditional(field, value, operator) {
  return `data['${field}'] ${operator} ${value}`
}

function _fn(condition) {
  return new Function('...args', `let [data] = args; return ${condition}`)
}

const data = {
  foo: 123
}

const fn = _fn(_conditional('foo', 321, '+'))
console.log(fn(data)) // 444
```
