### ISSUE TITLE
Event on EQCSS finishing initial work

### ISSUE THREAD

**Issue by magicznyleszek** [eqcss/eqcss#79]
I would like to have an option to display content only after EQCSS finishes setting up, so to avoid flash of not-fully-styled-content ;-)

**Comment by tomhodgins** [comment]
Hi! I've written a little bit about this here: [How to avoid FOUC with EQCSS](https://codepen.io/tomhodgins/post/how-to-avoid-fouc-with-eqcss)

The basic idea is that if you hide (`opacity: 0`) elements that will be gaining JS-powered styles, you can then set the `opacity` to `1` using JS once the other styles have been run.

```html
<script src=http://elementqueries.com/EQCSS.js></script>

<div>Hello</div>

<style>
  div {
    opacity: 0;
    transition: opacity .2s ease-in-out;
  }
  @element div {
    $this {
      color: red;
      opacity: 1;
    }
  }
</style>
```

Another thing to note here - adding EQCSS as early as you can in HTML (putting it in the `<head>` rather than at the end of the `<body>` can make a difference to how things load in as well. Try rearranging the location of where EQCSS is linked in and see if that helps any!

**Comment by magicznyleszek** [comment]
This makes sense, will do that, thanks :-)
