### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by tobireif** [eqcss/eqcss#84]
Hi!

In the current version of https://tobireif.com/demos/grid/ , when you resize the window slowly, there's a phase where the h1 is flickering a lot.

I had to bypass throttling because otherwise the :before and :after content would get adjusted only after a delay (so I need immediate calculations) (and don't want throttling anyways 😀).

I tried a lot but can't get rid of the flickering.

Even removing this doesn't help:
```
  h1:before, h1:after {
    content: none;
  }
```

During slow resizing, when the element is around the specified width (262px), the font size still flickers/jumps a lot, during a whole phase of resizing

Any ideas?

**Comment by tobireif** [comment]
(Could this get improved in the lib, perhaps?)

**Comment by tomhodgins** [comment]
Hmmm, what is this demo trying to accomplish? It seems there's a bit of circularity at a range of widths where applying the rule makes it so other rules no longer apply. You should be able to restructure the code so that there's no gap in what logically works, but I'm not sure how to refactor this without knowing the original goal.

**Comment by tobireif** [comment]
It's the super-early stage of a CSS Grid layout 😀

The h1 font size should be based on the h1 element width (as specified in the media query), at all times / widths.

Even during slow resizing there should be no flickering.

The element query:

```
@element h1 and (max-width: 262px) {
  /* ... even without this deleted code here there's flickering ... */
  h1 {
    font-size: 39.1ew;
    margin-left: -2px;
  }
}

```

I tried a lot, and would next revert back to @media queries if there's no solution / no way to prevent the flickering I get with element queries / EQCSS.

**Comment by tomhodgins** [comment]
But in this case you're setting the `h1`'s font size based on its width (`ew`) based on its width (`max-width`). I assume you're doing this because you want it to look or behave a certain way. If you can describe what you want it to look and behave like I'm sure we can write a query for it that does what you want without depending on `ew` and `max-width` for `font-size` at the same time :D

Perhaps setting the `h1`'s font-size based on the `max-width` of a containing element? Or perhaps setting the `h1`'s font-size using a unit that's not dependent on its own width could be two possibilities…

**Comment by tobireif** [comment]
> Perhaps setting the h1's font-size based on the max-width of a containing element?

This works beautifully - thank you very much!

And thanks for EQCSS!

May the W3C soon adopt your proposal and syntax ...
(But they seem to see fundamental issues with element queries: https://www.xanthir.com/b4PR0 )

**Comment by tobireif** [comment]
(This is off-topic for this issue ticket, but regarding W3C adoption:
This comment by Tab Atkins makes me more hopeful than the post on that page:
https://www.xanthir.com/b4PR0#4PR0-27 )
