### ISSUE TITLE
Combining multiple @element-querries

### ISSUE THREAD

**Issue by SlawaGurevich** [eqcss/eqcss#89]
Hi guys,

is it possible to combine multiple @element-querries. What I'm thinking of is something like

```
@element ".button__container" and (min-children:3){ 
  @element ".button" and (min-width:276px) {
    :self {
      width: 100%; 
    }
     
    :parent {      
      flex-basis: 476px;
    }
  }
}
```

I would like to apply the style to the buttons, but only if the button__container has more than 2 buttons.
However, this doesn't seem to work.

Regards
Slawa

**Comment by tomhodgins** [comment]
Hi @SlawaGurevich, No, I'm sorry but it's not possible with EQCSS to nest `@element` queries inside of each other. The first step the plugin does is extracting all of the `@element` queries it finds and registering them one-by-one with the plugin, this means that it finds sees both of your queries as 'top-level' queries totally independent of each other, and will trigger them whenever their individual conditions are met. This isn't a limitation of the concept of using element queries, but is a limitation with our plugin and how styles are read.

If you want to do this functionality in EQCSS you can, but you'll need to rewrite one of the queries from being an element query to a 'selector resolver' using `eval("")` and writing JS-based test similar to `(min-children: 3)` instead. If we queried all `.button__container .button` elements, that will give us an opportunity to test if any that are over `276px` wide have parents with 3+ children. Here's a demo:

```html
<nav class=button__container>
  <button class=button style=width:100px>Button</button>
  <button class=button style=width:200px>Button</button>
  <button class=button style=width:300px>Button</button>
</nav>

<style>
  @element ".button__container .button" and (min-width: 276px) { 

    eval('parentNode.children.length >= 3 && ":self"') {
      background: lime;
    }

  }
</style>

<script src=http://elementqueries.com/EQCSS.js></script>
```

Let me explain that `eval("")` a little bit, we're running a test on each `.button__container .button` in our document, and if its `parentNode` has 3 or more children, the `&&` connects and we end up with this in our EQCSS:

```css
:self {
  background: lime;
}
```

Which gets applied to each matching element. If for a given element the condition is not met our expression evaluates to `false`, so it will output this in our EQCSS query:

```css
false {
  background: lime;
}
```

And since there's no `<false>` tag in HTML, it's not going to match our elements. If having that text output in your stylesheet that bothers you, you can use a ternary instead to make sure that an empty string shows up instead when the test fails, like `parentNode.children.length >= 3 ? ":self" : ""` too.

You can go so far as to include the CSS rule inside the `eval("")` too if you want to ensure that there isn't even a rule present in your CSS when the test fails. You could put the entire rule for `:self` inside the `eval("")` quoted as a JS template string and just think of this as being an `eval("")`-supplied rule inside your top-level `@element` query:

```css
eval('parentNode.children.length >= 3 ? `

  :self {
    background: lime;
  }

`: ""') 
```

But, there are also more flexible ways of expressing and nesting element queries than the syntax EQCSS supports too. Similar to your original example I can use [jsincss](https://github.com/tomhodgins/jsincss) and [jsincss-element-query](https://github.com/tomhodgins/jsincss-element-query) to nest element queries like you originally wanted:

```html
<nav class=button__container>
  <button class=button style=width:100px>Button</button>
  <button class=button style=width:200px>Button</button>
  <button class=button style=width:300px>Button</button>
</nav>

<script type=module>
  import jsincss from 'https://unpkg.com/jsincss/index.js'
  import element from 'https://unpkg.com/jsincss-element-query/index.js'
  
  jsincss(()=>`
  
    ${element('.button__container', {minChildren: 3}, `
    
      ${element('.button', {minWidth: 276}, `
      
        :self {
          background: lime;
        }
      
      `)}
    
    `)}
  
  `)
</script>
```

In this case we're writing a stylesheet outside of our `jsincss-element-query` plugin, so we're able to call it two times (actually, we can call it as many times as we want) at as many different 'levels' as we want, rather than being limited to 'top-level' queries only. Here is the syntax for just the element queries isolated from the rest of the demo:

```js
${element('.button__container', {minChildren: 3}, `

  ${element('.button', {minWidth: 276}, `
  
    :self {
      background: lime;
    }
  
  `)}

`)}
```

It's not so different from EQCSS. The syntax here should be similar enough to EQCSS to see what each part is doing :D Hope this helps!
