### ISSUE TITLE
Support for @import inside of <style> tag

### ISSUE THREAD

**Issue by jsheffers** [eqcss/eqcss#92]
I was trying to implement this on a Drupal site and found out that it doesn't work when the file is using `@import`.  Drupal loads all CSS files like so:

```
<style type="text/css">
@import url("someurl.css");
@import url("someurl2.css");
</style>
```
In this case it appears as if EQCSS doesn't actually look inside of the file `someurl2.css`.  It does however add the element attribute to the <style> tag `data-eqcss-read="true"` but it doesn't actually find any data.  I did a quick search in the issue queue and I couldn't find anything about this.

If anyone else is interested in a Drupal specific fix,  I used this module to render my theme CSS as <link> instead of @import and it fixed the issue.  https://www.drupal.org/project/link_css

**Comment by tomhodgins** [comment]
Ooh that's really bad. Before I get to the EQCSS part I have to say that using `@import` is just about _the worst_ thing you can do for website loading performance. It's render-blocking. Normally when you load and HTML page when it encounters things like `<link>` or `<script>` tags it can begin fetching those files. If it finds multiple `<link>` or `<script>` tags it can even download those files simultaneously.

Now a note on how the browser handles CSS - no matter how many `<style>` tags or `<link>` tags as you have in the document, by the time the page is done loading you the browser has basically concatenated them into one giant CSS stylesheet, based on the order they appear in your HTML. So we know that the browser can't read the _next_ line of CSS until it has figured out what's on the current line of CSS.

When when you have a stylesheet that looks like this:

```css
@import url(one.css);
@import url(one.css);
h1 {}
```

Here's where it gets bad. The browser sees line 1 start with `@import` so it pauses everything while it goes to fetch `one.css`. It has to make a network request and download all of `one.css` and get to the end of that stylesheet before it can move on to the next line, which imports a second file `two.css`, make the network request, hope it downloads fast and completely, before it can ever move onto your style written in that stylesheet for the `h1`.

But if you have code like this:

```html
<link rel=stylesheet href=one.css>
<link rel=stylesheet href=two.css>
<link rel=stylesheet href=main.css>
```

The browser can be downloading `one.css`, `two.css`, and `main.css` simultaneously. Even though it can't move on to processing `two.css` it can be fully downloaded before the browser is ready to process it.

So no matter what you do with EQCSS you need to eliminate the `@import` in your CSS stylesheets and link in your CSS stylesheets either as `<style>` tags or `<link>` tags in your HTML.

Now, for EQCSS, it only reads `@element {}` queries from the contents of `<style>` tags, or the contents of files loaded via `<link rel=stylesheet>` and `<script type=text/eqcss>`, so if the `@element` isn't appearing directly in the content, it can't be parsed.

Alternatively, queries can be loaded and parsed by Javascript without even being in a stylesheet, and then directly added to the plugin as it's running in the browser.

If you were using JavaScript to parse your styles you can do something like this:

```html
<script src=http://elementqueries.com/EQCSS.js></script>

<script>
  let query = EQCSS.parse(`
    @element html and (min-width: 50px) {
      :self {
        background: lime;
      }
    }`)

  console.log(query)
</script>
```

Here I'm putting the query right in JavaScript and using `EQCSS.parse()` to parse it. I can then take the parsed query and use `EQCSS.register()` to load it into the plugin. There's also `EQCSS.process()` which both parses and registers a string containing `@element` queries if you want to do both, but `EQCSS.register()` can also work with `@element` queries that have been parsed in advanced and are served as JS files rather than as CSS files.

There's also a package called [eqcss-parse](https://www.npmjs.com/package/eqcss-parse) that will let you parse out the EQCSS syntax from a file and store it as JS objects that can be loaded into the EQCSS.js plugin as it's running on the page with `EQCSS.register()`.

Hope that helps shed some light on the ways you can use EQCSS, and also that CSS's `@import` should be avoided at all costs everywhere (separately from this issue) <3

**Comment by jsheffers** [comment]
Ok, thanks for the in-depth response.  In production environments, Drupal minifies all assets and references them with `<link>` so this is really only an issue for local development.
